source 'https://rubygems.org'
gem "webrick"
gem 'public_suffix', '3.0'
gem 'addressable', '2.8.5'
gem 'rexml', '3.2.6'
gem 'kramdown', '2.3.0'
gem "kramdown-parser-gfm"
gem 'rouge', '3.19.0'
gem 'jekyll', '3.9.0'
gem 'jekyll-archives', '2.1.1'
gem 'jekyll-sass-converter'
gem 'jekyll-feed', '0.13.0'
gem 'jekyll-seo-tag', '2.6.1'
gem 'jekyll-sitemap', '1.4.0'
gem 'jekyll-paginate', '1.1.0'
gem 'liquify', '0.2.7'
gem 'github-pages', '207'